ln -s ../../seaf-common/ seaf-common
ln -s ../../seaf-company-base/ seaf-company-base
ln -s ../../seaf-company-da/ seaf-company-da
ln -s ../../seaf-company-ta/ seaf-company-ta
ln -s ../../seaf-company-artefacts/ seaf-company-artefacts
ln -s ../../seaf-company-ai/ seaf-company-ai
ln -s ../../seaf-company-kadzo/ seaf-company-kadzo
ln -s ../../seaf-toolkit-mm_viewer/ seaf-toolkit-mm_viewer
ln -s ../../seaf-docs/ seaf-docs